#!/usr/bin/env bash

# The linux binary generated by build.sh is a dynamically linked executable. On NixOS these cannot be run as-is, because NixOS does not provide the necessary runtime libraries by default.

# This script runs the Linux target in a Nix FHS environment to provide 
# the necessary runtime libraries (GTK, X11, etc.)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HELOWORLD_EXE="$SCRIPT_DIR/assets/linux/HelloWorld"

if [ ! -f "$HELOWORLD_EXE" ]; then
    echo "Error: Binary not found at $HELOWORLD_EXE"
    echo "Please run build.sh first."
    exit 1
fi

nix-shell -E '
  let 
    pkgs = import <nixpkgs> {}; 
    fhs = pkgs.buildFHSEnv {
      name = "debian10-fhs";
      targetPkgs = pkgs: with pkgs; [
        libjpeg_turbo
        gtk3
        glib
        pango
        cairo
        gdk-pixbuf
        atk
        xorg.libX11
        xorg.libSM
        xorg.libICE
        xorg.libXext
        xorg.libXrender
        xorg.libXtst
        dbus
        fontconfig
        freetype
        libGL
        libxkbcommon
        libpng
        libz
      ];
    };
  in pkgs.mkShell {
    nativeBuildInputs = [ fhs ];
  }' --run "debian10-fhs -c \"$HELOWORLD_EXE\""
